// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZ5lItp0uAHgpKE05j4zc68hH4ZG3ipk',
    appId: '1:813352961447:web:130135e038d53eca2da282',
    messagingSenderId: '813352961447',
    projectId: 'shopping-51b00',
    authDomain: 'shopping-51b00.firebaseapp.com',
    storageBucket: 'shopping-51b00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPO6At08SunX-oDLzkQYX3tTUpN9nUCc4',
    appId: '1:813352961447:android:1b7bfb830f1b51df2da282',
    messagingSenderId: '813352961447',
    projectId: 'shopping-51b00',
    storageBucket: 'shopping-51b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ciV08o4bDylre_hFlsYqpb3PUqJSdtg',
    appId: '1:813352961447:ios:cbca4a08ff82f3a52da282',
    messagingSenderId: '813352961447',
    projectId: 'shopping-51b00',
    storageBucket: 'shopping-51b00.appspot.com',
    iosClientId: '813352961447-jdt5l8rljpifigge8mc73hj9funoc13t.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
